package com.simple.phonetics

val DEFAULT_TRANSLATE = mapOf(
    "action_check" to "Check",
    "action_clear" to "Clear",
    "action_confirm_change_language" to "Change phonetic language",
    "action_continue" to "Continue",
    "action_play_game" to "Play game",
    "action_retry" to "Try again",
    "action_reverse" to "Reverse",
    "action_try_speak" to "Try speak",
    "action_view_all_ipa" to "View all",

    "hint_enter_language_text" to "Enter \$language_name here!",
    "hint_enter_text" to "Enter text here!",

    "ipa_c" to "Central",
    "ipa_de" to "German",
    "ipa_eo" to "Esperanto",
    "ipa_es_es" to "Spanish (Spain)",
    "ipa_es_mx" to "Spanish (Mexico)",
    "ipa_fa" to "Persian",
    "ipa_fi" to "Finnish",
    "ipa_fr_fr" to "French (France)",
    "ipa_fr_qc" to "French (Québec)",
    "ipa_is" to "Icelandic",
    "ipa_ja" to "Japanese",
    "ipa_jam" to "Jamaican Creole",
    "ipa_km" to "Khmer",
    "ipa_ko" to "Korean",
    "ipa_ma" to "Malay (Malaysian and Indonesian)",
    "ipa_n" to "Northern",
    "ipa_nb" to "Norwegian Bokmål",
    "ipa_nl" to "Dutch",
    "ipa_or" to "Odia",
    "ipa_ro" to "Romanian",
    "ipa_s" to "Southern",
    "ipa_sv" to "Swedish",
    "ipa_sw" to "Swahili",
    "ipa_tts" to "Isan",
    "ipa_uk" to "English - UK",
    "ipa_us" to "English - US",
    "ipa_yue" to "Cantonese",
    "ipa_zh_hans" to "Simplified Chinese",
    "ipa_zh_hant" to "Traditional Chinese",

    "language_ar" to "Arab",
    "language_de" to "Germany",
    "language_en" to "English",
    "language_eo" to "Esperanto",
    "language_es" to "Spain, Mexico",
    "language_fa" to "Iran",
    "language_fi" to "Finland",
    "language_fr" to "France, Québec",
    "language_is" to "Iceland",
    "language_ja" to "Japan",
    "language_jam" to "Jamaican Creole",
    "language_km" to "Cambodia",
    "language_ko" to "South Korea",
    "language_ma" to "Malaysia, Indonesia",
    "language_nb" to "Norway",
    "language_nl" to "Netherlands",
    "language_or" to "India",
    "language_ro" to "Romania",
    "language_sv" to "Sweden",
    "language_sw" to "Swahili",
    "language_tts" to "Thailand",
    "language_vi" to "Vietnamese",
    "language_zh" to "Chinese",

    "message_completed_sync_phonetics" to "Phonetics \$ipa_name synchronized successfully",
    "message_completed_sync_translate" to "Translation synchronized successfully",
    "message_result_empty" to "No content yet!",
    "message_select_language" to "Select the language you want to find phonetics for",
    "message_start_sync" to "Starting synchronization...",
    "message_start_sync_phonetics" to "Synchronizing phonetics \$ipa_name \$percent%",
    "message_start_sync_translate" to "Synchronizing translation \$percent%",
    "message_support_translate" to "Translation supported",
    "message_sync_completed" to "Synchronization completed",
    "message_translate_download" to "Downloading translation...",

    "rate_action_negative" to "Late",
    "rate_action_positive" to "Rate",
    "rate_message" to "We'd love your feedback to make the app even better. Your review means a lot! 🌟",
    "rate_title" to "Rate app",

    "update_action_negative" to "⏳ Later",
    "update_action_positive" to "⚡ Update now",
    "update_message" to "✨ A new version is ready! 🚀 Update now for a smoother experience and exciting new features! 🎉",
    "update_title" to "🔄 App Update",

    "resource_history" to "From the search history",
    "resource_popular" to "From the popular list",

    "speed_lever" to "Speed \$lever",

    "title_game" to "Game Ipa 🎮",
    "title_answer_failed" to "Not quite right",
    "title_answer_true" to "Awesome",
    "title_history" to "History:",
    "title_ipa" to "Ipa:",
    "title_language" to "Select language",
    "title_phonetic" to "Phonetic:",
    "title_result" to "Result:",
    "title_translate" to "Translate:",
    "title_voice" to "Voice:",
    "title_voice_speed" to "Voice speed:",

    "translating" to "Translating",
    "translate_failed" to "Translation failed",

    "type_ipa" to "Transcription",
    "type_text" to "Letter",
    "type_voice" to "Pronounce",

    "voice_index" to "Voice \$index",

    "game_config_screen_action_play_game" to "Start playing now!",
    "game_config_screen_message_resource_from_history" to "Based on previously searched words",
    "game_config_screen_message_resource_from_popular" to "Based on commonly used words",
    "game_config_screen_message_resource_limit" to "Cannot select due to insufficient words",
    "game_config_screen_title_resource" to "Select game source",

    "game_congratulation_screen_action" to "Let's continue!",
    "game_congratulation_screen_message" to "Awesome! You've answered correctly \$number times in a row! Keep going and don't lose your streak! 😆👏",
    "game_congratulation_screen_message_1" to "Incredible! You've got \$number correct answers in a row! It'd be a shame to miss now! 🤭🔥",
    "game_congratulation_screen_message_2" to "You've answered correctly \$number times in a row! Are you hacking? How are you this good? 🤔😂",
    "game_congratulation_screen_message_3" to "You've got \$number correct answers in a row! At this rate, you'll be a master soon! Don't stop now! 🔥🎯",
    "game_congratulation_screen_message_4" to "You've stepped onto the legendary path with \$number correct answers in a row! Now all you need is some fans! 🤩👏",
    "game_congratulation_screen_title" to "Congratulations! 🎉",
    "game_congratulation_screen_title_1" to "Impressive! 😁",
    "game_congratulation_screen_title_2" to "Unbelievable! 😎",
    "game_congratulation_screen_title_3" to "I bow before you! 🙇‍♂️",
    "game_congratulation_screen_title_4" to "A living legend! 🏆",

    "game_ipa_puzzle_screen_message_answer" to "The answer is: \$param1.",
    "game_ipa_puzzle_screen_title" to "The word \$param1 has the pronunciation \$param2, but it is incomplete. Please complete the missing part.",

    "game_ipa_wordle_screen_action" to "Check",
    "game_ipa_wordle_screen_action_continue" to "Continue",
    "game_ipa_wordle_screen_action_retry" to "Try again",
    "game_ipa_wordle_screen_message_answer" to "\$param1 of \$param2 is \$param3",
    "game_ipa_wordle_screen_title" to "Choose the correct \$param1 for \$param2 below?",
    "game_ipa_wordle_screen_title_answer_failed" to "Not quite right",
    "game_ipa_wordle_screen_title_answer_true" to "Awesome",

    "game_ipa_match_screen_title" to "Match the suitable pairs together",
    "game_ipa_match_screen_title_choose" to "The pairs",
    "game_ipa_match_screen_message_answer_correct" to "The pairs have been matched",
    "game_ipa_match_screen_message_answer_failed" to "Some pairs don't quite match",

    "game_screen_title" to "Game",

    "ipa_detail_screen_consonants_unvoiced" to "Consonants unvoiced",
    "ipa_detail_screen_consonants_voiced" to "Consonants voiced",
    "ipa_detail_screen_diphthongs" to "Diphthongs",
    "ipa_detail_screen_title_example" to "Example:",
    "ipa_detail_screen_vowels_long" to "Vowels long",
    "ipa_detail_screen_vowels_short" to "Vowels short",

    "ipa_list_screen_title" to "Ipa list",

    "recording_screen_title" to "Please speak \$language_name"
)